"""Rename ptitle column to title in Project table

Revision ID: 5688e1a1f761
Revises: e570c830c3e4
Create Date: 2024-03-20 14:13:01.254198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5688e1a1f761'
down_revision = 'e570c830c3e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faculty_fname'), ['fname'], unique=False)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_project_academic_year'), ['academic_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_amount_sanctioned'), ['amount_sanctioned'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_domain'), ['domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_duration'), ['duration'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_fid'), ['fid'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_title'), ['title'], unique=False)
        batch_op.drop_column('ptitle')
        batch_op.drop_column('student_year')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_year'), ['year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_year'))
        batch_op.drop_index(batch_op.f('ix_student_name'))

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_year', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('ptitle', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_index(batch_op.f('ix_project_title'))
        batch_op.drop_index(batch_op.f('ix_project_start_date'))
        batch_op.drop_index(batch_op.f('ix_project_fid'))
        batch_op.drop_index(batch_op.f('ix_project_duration'))
        batch_op.drop_index(batch_op.f('ix_project_domain'))
        batch_op.drop_index(batch_op.f('ix_project_amount_sanctioned'))
        batch_op.drop_index(batch_op.f('ix_project_academic_year'))
        batch_op.drop_column('title')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faculty_fname'))

    # ### end Alembic commands ###
