"""Add task_completed column to progress table

Revision ID: a0675146e105
Revises: 8e19e6c217f0
Create Date: 2024-05-08 14:52:27.448848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0675146e105'
down_revision = '8e19e6c217f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_completed', sa.Integer(), nullable=True, server_default='0'), name='task_completed')  # Adding a default value and providing a name
        batch_op.drop_column('grade', cascade=True)  # Dropping with cascade to handle dependent constraints
        batch_op.drop_column('overall_score', cascade=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_score', sa.INTEGER(), nullable=True, server_default='0'), name='overall_score')  # Adding a default value and providing a name
        batch_op.add_column(sa.Column('grade', sa.INTEGER(), nullable=True, server_default='0'), name='grade')  # Adding a default value and providing a name
        batch_op.drop_column('task_completed', cascade=True)  # Dropping with cascade to handle dependent constraints

    # ### end Alembic commands ###
