"""Add username column to faculty table

Revision ID: c03f6f88c9b3
Revises: a0675146e105
Create Date: 2024-05-10 20:33:47.333058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03f6f88c9b3'
down_revision = 'a0675146e105'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), default=False, nullable=False))
        batch_op.create_unique_constraint('uq_faculty_username', ['username'])  # Explicitly name the constraint

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_constraint('uq_faculty_username', type_='unique')  # Explicitly drop the named constraint
        batch_op.drop_column('username')
        batch_op.drop_column('password')
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
